In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split

# Chargement des données
iris = datasets.load_iris()
X, y = iris.data, iris.target
# On conserve 50% du jeu de données pour l'évaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [2]:
X, y = iris.data[:,:2], iris.target
# On conserve 50% du jeu de données pour l'évaluation
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [20]:
clf = svm.SVC(C=0.1, kernel='rbf', gamma=0.25)
clf.fit(X_train, y_train)

# Pour afficher la surface de décision on va discrétiser l'espace avec un pas h
h = .02
# Créer la surface de décision discretisée
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

print(xx)
print(yy)
# Surface de décision
#Z = clf.predict(np.c_[xx.ravel(), 0,0, yy.ravel()])


[[-1.   -0.98 -0.96 ...  0.94  0.96  0.98]
 [-1.   -0.98 -0.96 ...  0.94  0.96  0.98]
 [-1.   -0.98 -0.96 ...  0.94  0.96  0.98]
 ...
 [-1.   -0.98 -0.96 ...  0.94  0.96  0.98]
 [-1.   -0.98 -0.96 ...  0.94  0.96  0.98]
 [-1.   -0.98 -0.96 ...  0.94  0.96  0.98]]
[[-1.   -1.   -1.   ... -1.   -1.   -1.  ]
 [-0.98 -0.98 -0.98 ... -0.98 -0.98 -0.98]
 [-0.96 -0.96 -0.96 ... -0.96 -0.96 -0.96]
 ...
 [ 8.94  8.94  8.94 ...  8.94  8.94  8.94]
 [ 8.96  8.96  8.96 ...  8.96  8.96  8.96]
 [ 8.98  8.98  8.98 ...  8.98  8.98  8.98]]


In [4]:
from sklearn.datasets import load_digits
digits = load_digits()
X, y = digits.data, digits.target
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

(1797, 64)
(1797,)


In [14]:
# SVM à noyau gaussien
clf_svm_kernel = svm.SVC(C=0.1, kernel='rbf', gamma=0.25)
clf_svm_kernel.fit(X_train, y_train)

# Pour afficher la surface de décision on va discrétiser l'espace avec un pas h
h = .02
# Créer la surface de décision discretisée
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
print(xx.shape)
print(yy.shape)

# Surface de décision
Z = clf_svm_kernel.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

(500, 100)
(500, 100)


ValueError: X.shape[1] = 2 should be equal to 64, the number of features at training time

In [9]:
# SVM linear
C = 9.0
lin_svc = svm.LinearSVC(C=C)
lin_svc.fit(X_train, y_train)


C:\Users\Utilisateur\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC(C=9.0)